### ISSUE TITLE
invalid client when integrating Login Kit Android SDK

### ISSUE THREAD

**Issue by ovidiuvaro** [tiktok/tiktok-opensdk-android#13]
We integrated Android SDK and requested several scopes, but we are getting invalid client.

Everything was done exactly like in the demo.

<img width="1067" alt="Screenshot 2023-09-07 at 12 02 09" src="https://github.com/tiktok/tiktok-opensdk-android/assets/99169177/39d3719b-48d2-4472-a66e-d53dc8923cda">

**Comment by haifano** [comment]
Please make sure you have added all the products, scopes if you haven't yet, you can do this by going to the [TikTok for Developers website](https://developers.tiktok.com/), navigating to the Manage apps page, and clicking + Add products on your app configuration page. You have to submit your change for approval and you can test it once the change's approved.

**Comment by ovidiuvaro** [comment]
Sorry for not updating this, actually the problem was that I wasn't running the app from the play store release system, just building a product/debug application from IDE. In order to have a valid testing you'll have to run it from Play Store with MD5 and SHA-256 applied.
