### ISSUE TITLE
where to find java or python sdk

### ISSUE THREAD

**Issue by wanghaisheng** [tiktok/tiktok-opensdk-android#2]
https://developers.tiktok.com/doc/content-posting-api-reference-upload-video/
especially for content posting api

**Comment by haifano** [comment]
1. If you want to use the TikTok Login Kit and Share Kit features on your Android app, you can integrate the Android SDK into your Java Android project by following the instructions here: https://developers.tiktok.com/doc/mobile-sdk-android-quickstart/
2. We currently don't provide SDKs for our Open API (Content Posting API, Display API, and Research API). We suggest following the specific instructions in the following guides to integrate the API into your app:
  - Content Posting API: https://developers.tiktok.com/doc/content-posting-api-get-started/
  - Display API: https://developers.tiktok.com/doc/display-api-get-started/
  - Research API: https://developers.tiktok.com/doc/research-api-get-started/
