### ISSUE TITLE
login error errorCode=10004, errorMsg=server_error

### ISSUE THREAD

**Issue by pangli** [tiktok/tiktok-opensdk-android#6]
![image](https://github.com/tiktok/tiktok-opensdk-android/assets/7498978/84542e1f-8986-4c8a-a7ca-066bbca49c73)
![image](https://github.com/tiktok/tiktok-opensdk-android/assets/7498978/6d18e487-54a5-45e4-9f8b-bc4a158ea03d)
return
AuthResponse(authCode=, state=null, grantedPermissions=, errorCode=10004, errorMsg=server_error, extras=null, authError=server_error, authErrorDescription=null)

**Comment by youngKimTikTok** [comment]
When testing with your own project, be sure to add Login Kit before you attempt to use Login Kit. You can do this by going to the [TikTok Developers website](https://developers.tiktok.com/), navigating to the Manage apps page, and clicking '+' Add  on your app configuration page.
![Issue6_image1](https://github.com/tiktok/tiktok-opensdk-android/assets/115035012/312761ef-f5e9-4663-839c-e3dfc8fb6c2f)
If you need more assistance to debug, please fill out the [feedback form](https://developers.tiktok.com/support/) with other detailed information.

**Comment by pangli** [comment]
> When testing with your own project, be sure to add Login Kit before you attempt to use Login Kit. You can do this by going to the [TikTok Developers website](https://developers.tiktok.com/), navigating to the Manage apps page, and clicking '+' Add on your app configuration page. ![Issue6_image1](https://user-images.githubusercontent.com/115035012/253120792-312761ef-f5e9-4663-839c-e3dfc8fb6c2f.jpeg) If you need more assistance to debug, please fill out the [feedback form](https://developers.tiktok.com/support/) with other detailed information.

I have added Login Kit and TikTok API. still can't login for debugging, do I need to approve the app before I can test it?

![image](https://github.com/tiktok/tiktok-opensdk-android/assets/7498978/a7376fc6-b5b2-4dd6-9fce-4b34efc9321c)

![image](https://github.com/tiktok/tiktok-opensdk-android/assets/7498978/a50841a7-726e-473e-99b3-1380c52586a7)

**Comment by youngKimTikTok** [comment]
Firstly, thanks for your patience. Yes, your apps must be reviewed and approved before testing. Please submit your requests for further testing.

**Comment by pangli** [comment]
> Firstly, thanks for your patience. Yes, your apps must be reviewed and approved before testing. Please submit your requests for further testing.

Thanks, but I only access TikTok Login on Android or iOS, when I submit the app for review, it is always rejected asking me to fill in the Website URL on the web side, I don't have access on the web side, why do I have to fill in this?
![image](https://github.com/tiktok/tiktok-opensdk-android/assets/7498978/d2148434-0588-4e1d-8beb-7e928e5c83c6)
