### ISSUE TITLE
onNewIntent not called

### ISSUE THREAD

**Issue by pangli** [tiktok/tiktok-opensdk-android#8]
application onNewIntent is not called.
AuthApi.AuthMethod.ChromeTab when closing the browser can not know whether the result is cancellation of the authorization
![image](https://github.com/tiktok/tiktok-opensdk-android/assets/7498978/2bf5d3b5-fbb0-43e0-bca7-f9a43b51bd04)

**Comment by haifano** [comment]
This is a known issue as we are unable to detect the close event for a custom Chrome tab. The `onResume` function of the caller activity should be triggered if users close the Chrome tab by clicking the close button or pressing the back button, and you can handle the cancel even there.

**Comment by pangli** [comment]
Customise an interface, set up markers to handle it and you're done!
